language: c
env:
    KERNEL=3.8
    KERNEL=3.10
    KERNEL=3.14
before_script:
    - export JOBS=3
    - sudo apt-get install libglib2.0-dev libsdl1.2-dev libjpeg-dev libvde-dev libvdeplug2-dev libbrlapi-dev libaio-dev libfdt-dev texi2html texinfo info2man pod2pdf libnss3-dev libcap-dev libattr1-dev gcc-4.6-multilib bc
    - sudo apt-get install screen
    - wget http://wiki.qemu-project.org/download/qemu-1.5.0.tar.bz2 -O - | tar xjf -
    - cd qemu-1.5.0/
    - ( ./configure --prefix=/usr --enable-linux-aio --target-list=x86_64-softmmu --disable-strip --disable-xen  --disable-kvm --disable-user --disable-docs  && make -j$JOBS && sudo make install ) >/dev/null
    - cd ..
    - wget https://www.kernel.org/pub/linux/kernel/v3.x/linux-${KERNEL}.tar.gz
    - tar xf linux-${KERNEL}.tar.gz
    - make -C linux-${KERNEL} mrproper
    - printf "Host qemu\n\tHostname 127.0.0.1\n\tPort 60022\n\tUser root\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
    - ./run_vm &
    - while sleep 1; do ssh qemu 'true' 2>&1 >/dev/null && break; done
    - ssh -q qemu 'zcat /proc/config.gz' > linux-${KERNEL}/.config
    - yes '' | make -C linux-${KERNEL} oldconfig >/dev/null
    - make -j$JOBS -C linux-${KERNEL}
    - scp linux-${KERNEL}/arch/x86/boot/bzImage qemu:/boot
script:
    - make -j$JOBS -C linux-$[KERNEL} M=`pwd`
    - cat record.ko | ssh qemu 'cat > record.ko'
    - ssh qemu 'reboot'
    - while sleep 1; do ssh qemu 'true' 2>&1 >/dev/null && break; done
    - ssh qemu 'insmod record.ko'
    - ssh qemu 'rmmod record.ko'
