language: c
before_script:
    - sudo add-apt-repository -y ppa:serge-hallyn/qemu-p-migration
    - sudo apt-get update
    - sudo apt-get install qemu screen
script:
    - qemu-system-x86_64 --version
    - ./run_vm
    - sleep 5
    - printf "Host qemu\n\tHostname 127.0.0.1\n\tPort 60022\n\tUser root\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
    - ssh qemu 'zcat /proc/config.gz'
